// <auto-generated />
namespace CeniraBiblioteca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Libros : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Libros));
        
        string IMigrationMetadata.Id
        {
            get { return "201407302241499_Libros"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
